とうろくふぉーむつくったよ
shimauma0312/TaNaRi-Chan pull request #92
Opened 2024-12-05 04:40 UTC by asa-cording

### 該当イシュー
 #10 

### 作業ブランチ
feature-todoRegister

### 作業場所
src/app/dashboard/todoList/register

### 実装した機能
- ダッシュボードからフォームに遷移するボタン
- todoを登録するフォーム
乗っける入力
todoタイトル
説明文
期限
公開範囲(自分のみか全体公開か)
- スタイリング
＊送信はボタンだけ置いてくれればおｋ。後ろの実装は後で

2024-12-05 05:33 UTC, shimauma0312 commented on package.json
謎のpackage.json、、、、

2024-12-05 10:04 UTC, asa-cording commented on package.json
やべ、気づかなかった、、、
けしときます

2024-12-05 15:18 UTC, shimauma0312 commented on package.json
git resetでログごと消せますか？🚧

2024-12-06 09:51 UTC, asa-cording commented on package.json
ワークツリー変わってどこまでリセットすればいいかわからなくなった・・・
クローンからやり直して大丈夫？

2024-12-06 10:58 UTC, shimauma0312 commented on package.json
普通に[be381bc](https://github.com/shimauma0312/TaNaRi-Chan/pull/92/commits/be381bcbe9eb1fdd4e06c6f9e459006c9249a1f0)のコミットまでリセットすればいいと思います

参考　https://www.r-staffing.co.jp/engineer/entry/20191129_1

多分その時src/app/dashboard/todoList/register/page.tsxが消えちゃうと思いますが、手動で再作成していただければ

2025-02-02 10:49 UTC, shimauma0312 requested changes
フォームに飛べるボタンを/todolistにおいてほしいです➡

2025-02-02 10:49 UTC, shimauma0312 commented on src/app/dashboard/todoList/register/page.tsx
> +        ダッシュボードへ戻る
ダッシュボードじゃなくてtodolistに戻るようにしたほうがいいですね。

2025-02-02 12:15 UTC, atamu2463 commented
画面こんな感じ

dashboard/todoList
![image](https://github.com/user-attachments/assets/f0ef3426-cc49-466c-b8f0-e5dfe7624e1f)

/todoList/register
![image](https://github.com/user-attachments/assets/9211e6ab-38fb-4500-b1b7-fdc4eb50a0c4)

2025-02-02 23:57 UTC, shimauma0312 approved these changes
おｋ

2025-02-02 23:58 UTC, merged